spin_manifest_version = 2

[application]
authors = ["Your Name"]
name = "Coingecko Oracle"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
sequencer = "http://sequencer:8877/post_report"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
reporter_id = 0

[[trigger.oracle]]
component = "coingecko"

[[trigger.oracle.data_feeds]]
data = '{"gecko_id":"bitcoin","vs_currency":"usd"}'
id = "31"

[[trigger.oracle.data_feeds]]
data = '{"gecko_id":"ethereum","vs_currency":"usd"}'
id = "47"

[[trigger.oracle.data_feeds]]
data = '{"gecko_id":"tether","vs_currency":"eur"}'
id = "253"

[[trigger.oracle.capabilities]]
data = "CG-fm6Li1hufZKJHaGUBRqPp1Up"
id = "GECKO_API_KEY"

[component.coingecko]
source = "target/wasm32-wasi/release/gecko_oracle.wasm"
allowed_outbound_hosts = [
  "https://api.coingecko.com"
]

[component.coingecko.build]
command = "cargo build --target wasm32-wasi --release" 